server:
  port: 8080
  servlet:
    path: "/"
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/csdn?useUnicode=true&characterEncoding=utf8"
    username: "root"
    password: "root"
  jpa:
    hibernate:
      database: "MySQL"
      show-sql: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  mvc:
   view:
    prefix: /
    suffix: .jsp
    viwe-names: jsp/
   static-path-pattern: /**
  servlet:
    multipart:
      max-file-size: "10MB"
      max-request-size: "100MB"

  thymeleaf:
    prefix: /
    suffix: .html
    view-names: /*
    check-template-location: "true"
    encoding: "UTF-8"
    mode: "LEGACYHTML5"
    cache: false
    servlet:
      content-type: "text/html"

